language: cpp
sudo: required
dist: trusty
os:
- linux

matrix:
    include:
        - os: linux
          dist: xenial
          env:
           - CXX_COMPILER=/usr/bin/g++-7
           - C_COMPILER=/usr/bin/gcc-7
          addons:
            apt:
                sources:
                - ubuntu-toolchain-r-test
                packages:
                - g++-7
                - pandoc
        - os: linux
        
before_install:
- if [ -n "${C_COMPILER}" ]; then sudo update-alternatives --install /usr/bin/gcc  gcc "${C_COMPILER}"  90; fi
- if [ -n "${CXX_COMPILER}" ]; then sudo update-alternatives --install /usr/bin/g++  g++ "${CXX_COMPILER}"  90; fi

script:
# Build
  - cd src/
  - make install
# Run tests

# notifications
