language: cpp
sudo: required
dist: trusty
os:
- linux

matrix:
    include:
        - os: linux
          dist: xenial
          env:
           - CXX_COMPILER=/usr/bin/g++-7
           - C_COMPILER=/usr/bin/gcc-7
          addons:
            apt:
                sources:
                - ubuntu-toolchain-r-test
                packages:
                - g++-7
                - pandoc
        - os: linux

script:
# Build
  - cd src/
  - make install
# Run tests

# notifications
